CREATE DATABASE InLock_Games_Tarde

USE InLock_Games_Tarde

CREATE TABLE ESTUDIOS (
	EstudioId INT IDENTITY PRIMARY KEY NOT NULL
	,NomeEstudio VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE JOGOS (
	JogoId INT IDENTITY PRIMARY KEY NOT NULL
	,NomeJogo VARCHAR(150) NOT NULL UNIQUE
	,Descricao TEXT NOT NULL
	,DataLancamento DATE NOT NULL
	,Valor DECIMAL(10,2) NOT NULL
	,EstudioId INT FOREIGN KEY REFERENCES ESTUDIOS(EstudioId) NOT NULL
);

CREATE TABLE USUARIOS (
	UsuarioId INT IDENTITY PRIMARY KEY NOT NULL
	,Email VARCHAR(200) NOT NULL UNIQUE
	,Senha VARCHAR(255) NOT NULL
	,TipoUsuario VARCHAR(150) NOT NULL
);